general {
    lock_cmd = pidof hyprlock || hyprlock        # comando para lock screen
    before_sleep_cmd = loginctl lock-session         # travar antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on      # garantir que a tela ligue ao voltar
}

# Monitor desliga após 5 minutos (300 segundos)
listener {
    timeout = 300                                
    
    # Desliga o sinal de vídeo de TODOS os monitores (eDP-1 e HDMI-A-1)
    on-timeout = hyprctl dispatch dpms off
    
    # Liga todos os monitores ao voltar (mexer mouse/teclado)
    on-resume = hyprctl dispatch dpms on
}
