general {
    lock_cmd = notify-send "Sistema travado"          # comando para lock screen
    before_sleep_cmd = loginctl lock-session         # travar antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on      # garantir que a tela ligue ao voltar
}

# Monitor desliga após 5 minutos (300 segundos)
listener {
    timeout = 300                            
    # Comando alterado para garantir que todos os monitores desliguem
    on-timeout = hyprctl dispatch dpms off
    # Caso o de cima falhe no HDMI, este é o "plano B" mais forte:
    on-timeout = hyprctl keyword monitor HDMI-A-1,disable 
    
    on-resume = hyprctl dispatch dpms on
    # Reabilita o monitor externo ao voltar
    on-resume = hyprctl keyword monitor HDMI-A-1,1920x1080@60,1920x0,1 
}
