general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot # Usa um print da sua tela atual
    color = rgba(36, 39, 58, 1.0) # Cor base do Macchiato
    blur_passes = 2 # 0 desativa o desfoque
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Relógio
label {
    monitor =
    text = $TIME
    color = rgb(138, 173, 244) # Azul Safira
    font_size = 64
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

# Campo de Senha
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(138, 173, 244) # Sapphire
    inner_color = rgb(36, 39, 58) # Base
    font_color = rgb(202, 211, 245) # Text
    fade_on_empty = true
    placeholder_text = <i>Senha para o Lucas...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}
