preload = /home/lucas/wallpapers/arch-black.png
# Map the wallpaper specifically to your HDMI-A-1 monitor
wallpaper = HDMI-A-1,/home/lucas/wallpapers/arch-black.png
# Disable the splash text if you want it cleaner
splash = false
